baseURL = 'https://www.cc2024-eschelbronn.de'
defaultContentLanguage = 'de'
defaultContentLanguageInSubdir = true
title = 'Club Cycliste 2024 Eschelbronn'

theme = 'hugo-universal-theme'

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# allow html in markdown
[markup.goldmark.renderer]
  unsafe = false

# not pluralize title pages by default
pluralizelisttitles = false

[menu]

# Main menu
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

#------------------------------------------------------- Trainingszeiten ---------------
[[menu.main]]
    name       = "Aktivitäten"
    identifier = "menu.aktivitaeten"
    url        = "/de/aktivitaeten/aktivitaeten"
    weight     = 2

#------------------------------------------------------- VEREIN ---------------
[[menu.main]]
    name       = "Verein"
    identifier = "menu.verein"
 #   url        = "/img/template-easy-customize.png"
    weight     = 3

[[menu.main]]
    name       = "Über uns"
    url        = "/de/verein/ueber_uns/"
    weight     = 1
    parent     = "menu.verein"

[[menu.main]]
    name       = "Vorstand"
    url        = "/de/verein/vorstand/"
    weight     = 2
    parent     = "menu.verein"

[[menu.main]]
    name       = "Satzung"
    url        = "/de/verein/satzung"
    weight     = 3
    parent     = "menu.verein"

[[menu.main]]
    name       = "Satzung als PDF"
    url        = "/de/verein/satzung.pdf"
    weight     = 4
    parent     = "menu.verein"
[[menu.main.params]]
    external = true

#-------------------------------------------------------  Mitglied werden ------------

[[menu.main]]
    name       = "Mitglied werden"
    identifier = "menu.mitglied"
    url        = "/de/mitglied_werden/cce_mitgliedsantrag_2025.pdf"
    weight     = 4
[[menu.main.params]]
    external = true

#------------------------------------------------------- Alle Artiekl ---------------

[[menu.main]]
    name       = "Alle Artikel"
    identifier = "menu.artikel"
    url        = "/de/posts/"
    weight     = 5

#-------------------------------------------------------  Impressum  ------------

[[menu.main]]
    name       = "Impressum"
    identifier = "menu.impressum"
    url        = "/de/Impressum/Impressum"
    weight     = 6


#-------------------------------------------------------  TopBar  ------------
# Enable or disable top bar with social icons
# better disable to prevent a flood of spam-mails
[params.topbar]
    enable = true
     text = """<p class="hidden-sm hidden-xs" style="font-size: 20px; color: #acd2b5; font-family: Roboto, Helvetica, Arial, sans-serif;">Club Cycliste 2024 Eschelbronn</p>
     """
#    text = """<p class="hidden-sm hidden-xs">Kontaktiert uns über kontakt@cc2024-eschelbronn.de</p>
#      <p class="hidden-md hidden-lg"><a href="mailto:kontakt@cc2024-eschelbronn.de" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
#      </p>
#      """

[[menu.topbar]]
    weight = 1
    name = "Email"
    url = "mailto:kontakt@cc2024-eschelbronn.de"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[[menu.topbar]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/EnTaroAdunExecutar/CC2024-hugo-universal"
    pre = "<i class='fab fa-2x fa-github'></i>"

[params]

    defaultKeywords = ["Tour", "Rad"]
    mainSections = ["posts"]
    
    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "green"

    about_us = "<p>Das radelnde Schreinerdorf und sein Fahrradverein - Club Cycliste 2024 Eschelbronn</p>"
    copyright = "Copyright (c) 2024, Club Cycliste 2024 Eschelbronn, alle Rechte vorbehalten"

    # Logo
    disabled_logo = false
    logo_text = "Club Cycliste 2024 - Eschelbronn"
    logo = "Bilder/CCE_Wappen.png"
    logo_small = "Bilder/CCE_Wappen.png"

    dropdown_mouse_over = true

[params.footer.recent_posts]
    enable = true

[params.recent_posts]
    enable = true
    title = "Aktuelle Artikel"
#    subtitle = "aktuell Artikel "
    hide_summary = false

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = false
    tags = true
    search = false

### use this for something like a top news -> linking somewhere else
[params.see_more]
    enable = false 
    icon = "fa fa-file-alt"
    title = "Stadtradeln"
#    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
#   link_url = "https://www.stadtradeln.de/fileadmin/radelkalender/embed/radelmeter-team.php?sr_team_id=11694&L=0"
#   link_text = "Check other homepages"
#   url = "https://www.stadtradeln.de/fileadmin/radelkalender/embed/radelmeter-team.php?sr_team_id=11694&L=0"